export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SAVE_USERINFO = 'SAVE_USERINFO';
export const GET_PRODUCT_INFO='GET_PRODUCT_INFO';
export const SAVE_PRODUCT_PROPS='SAVE_PRODUCT_PROPS';
export const ADD_CART_PRODUCT = 'ADD_CART_PRODUCT';
export const REMOVE_CART_PRODUCT = 'REMOVE_CART_PRODUCT';
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY';

